services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digitalocean-ai-agent-discord-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/usr/src/app/logs
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
