services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digitalocean-ai-agent-discord-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/usr/src/app/logs
    networks:
      - bot-network
    healthcheck:
      test: [ "CMD", "node", "-e", "require('node:http').request('http://localhost:3000/health', { timeout: 2000 }, res => process.exit(res.statusCode === 200 ? 0 : 1)).end()" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  bot-network:
    driver: bridge
